import React from 'react';

export default function ToS() {
  return (
    <div style={{ background: 'linear-gradient(135deg, #0f1f3c 0%, #1a2f52 100%)', minHeight: '100vh', padding: '40px 20px' }}>
      <div style={{ maxWidth: '800px', margin: '0 auto', color: '#e8e8e8' }}>
        <a href="/" style={{ color: '#d4af37', textDecoration: 'none', fontWeight: 'bold', marginBottom: '20px', display: 'block' }}>← Back to Home</a>
        
        <h1 style={{ color: '#d4af37', marginBottom: '30px' }}>Terms of Service</h1>
        <p style={{ color: '#d4af37', fontStyle: 'italic' }}>Last Updated: August 2026</p>

        <section style={{ marginBottom: '40px' }}>
          <h2 style={{ color: '#d4af37', marginTop: '30px' }}>1. Acceptance of Terms</h2>
          <p>By accessing and using ListingFlow, you agree to be bound by these Terms of Service. If you do not agree to any part of these terms, you may not use our service.</p>
        </section>

        <section style={{ marginBottom: '40px' }}>
          <h2 style={{ color: '#d4af37', marginTop: '30px' }}>2. Service Description</h2>
          <p>ListingFlow is an AI-powered SaaS platform that generates real estate content, including MLS descriptions, social media captions, and open house flyers. The service is designed for licensed real estate professionals.</p>
        </section>

        <section style={{ marginBottom: '40px' }}>
          <h2 style={{ color: '#d4af37', marginTop: '30px' }}>3. User Eligibility</h2>
          <p>Users must be 18 years or older and a licensed real estate agent to use this service. You represent and warrant that you have the legal capacity to enter into this agreement.</p>
        </section>

        <section style={{ marginBottom: '40px' }}>
          <h2 style={{ color: '#d4af37', marginTop: '30px' }}>4. Account Registration</h2>
          <p>You agree to provide accurate, current, and complete information during registration. You are responsible for maintaining the confidentiality of your account credentials and password. You agree to notify us immediately of any unauthorized access to your account.</p>
        </section>

        <section style={{ marginBottom: '40px' }}>
          <h2 style={{ color: '#d4af37', marginTop: '30px' }}>5. Acceptable Use</h2>
          <p>You agree not to use ListingFlow for any unlawful purpose or in violation of any applicable laws or regulations. You will not attempt to reverse engineer, decompile, or discover the source code or underlying technology of ListingFlow.</p>
        </section>

        <section style={{ marginBottom: '40px' }}>
          <h2 style={{ color: '#d4af37', marginTop: '30px' }}>6. Intellectual Property</h2>
          <p>All content generated by ListingFlow, including text, images, and designs, is provided for your personal professional use. You retain rights to content you generate but grant ListingFlow a license to use such content for service improvement purposes.</p>
        </section>

        <section style={{ marginBottom: '40px' }}>
          <h2 style={{ color: '#d4af37', marginTop: '30px' }}>7. Payment Terms</h2>
          <p>Paid tiers (Standard and Pro Bilingual) are billed monthly. You authorize ListingFlow to charge your payment method on file. Billing will continue until you cancel your subscription.</p>
        </section>

        <section style={{ marginBottom: '40px' }}>
          <h2 style={{ color: '#d4af37', marginTop: '30px' }}>8. Cancellation and Refunds</h2>
          <p>You may cancel your subscription at any time. Refunds are not provided for partial months. Upon cancellation, you will lose access to paid features at the end of your billing period.</p>
        </section>

        <section style={{ marginBottom: '40px' }}>
          <h2 style={{ color: '#d4af37', marginTop: '30px' }}>9. Disclaimer of Warranties</h2>
          <p>ListingFlow is provided "as-is" without warranties of any kind. We do not warrant that the service will be uninterrupted or error-free. Generated content should be reviewed and edited by you before professional use.</p>
        </section>

        <section style={{ marginBottom: '40px' }}>
          <h2 style={{ color: '#d4af37', marginTop: '30px' }}>10. Limitation of Liability</h2>
          <p>In no event shall ListingFlow be liable for any indirect, incidental, special, or consequential damages arising from your use of the service, even if we have been advised of the possibility of such damages.</p>
        </section>

        <section style={{ marginBottom: '40px' }}>
          <h2 style={{ color: '#d4af37', marginTop: '30px' }}>11. Contact Information</h2>
          <p>For questions or concerns about these Terms of Service, please contact us at: <a href="mailto:supportlistingflow@gmail.com" style={{ color: '#d4af37', textDecoration: 'none', fontWeight: 'bold' }}>supportlistingflow@gmail.com</a></p>
        </section>

        <section style={{ marginBottom: '40px' }}>
          <h2 style={{ color: '#d4af37', marginTop: '30px' }}>12. Changes to Terms</h2>
          <p>ListingFlow reserves the right to modify these Terms of Service at any time. Your continued use of the service constitutes acceptance of any changes.</p>
        </section>
      </div>
    </div>
  );
}
